### ISSUE TITLE
Mockup CompanioAI

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-companion-ai#2]
Mockup: https://www.figma.com/file/l90dGNyMzI5GnuEJBQh3Yi/Untitled?type=design&node-id=0%3A1&mode=design&t=ieqeAVDi5GW0nA6p-1

Prototipo: https://www.figma.com/proto/l90dGNyMzI5GnuEJBQh3Yi/Untitled?type=design&node-id=82-191&t=3lpbVLExEGNfoZgi-1&scaling=min-zoom&page-id=0%3A1&mode=design

Reporte: 
[Reporte de Makucp.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-companion-ai/files/14314923/Reporte.de.Makucp.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
Honestamente no sabría que calificación asignarles ya que la rúbrica pide evaluar el reporte de práctica, mismo que no encontré en este repositorio, por ende dejo a disposición la calificación otorgada por el docente.

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, tienen un total de 60 puntos de 100, ya que les faltó más imágenes con su respectiva descripción, en sus resultados y conclusiones únicamente tienen 5 líneas en un mínimo de 6.

**Comment by josealfredo79** [comment]
@Daniel-Velasco-Lopez Gracias por la sugerencias...

**Comment by josealfredo79** [comment]
Calificacion final 16
